spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
    application:
      name: microservicecloud-config-study-dev
---
spring:      
  profiles: test
    application:
      name: microservicecloud-config-study-test
